import { Geist, Geist_Mono } from "next/font/google";
import QueryClientProviderLayout from "@/lib/providers/query-client.provider";
import { Metadata } from "next";
import "./globals.css";
import AntdProviderLayout from "@/lib/providers/antd.provider";
// import "@ant-design/v5-patch-for-react-19";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <AntdProviderLayout>
          <QueryClientProviderLayout>{children}</QueryClientProviderLayout>
        </AntdProviderLayout>
      </body>
    </html>
  );
}
